#!/usr/bin/env bash

set -euo pipefail

REPORT_DIR="reports"
REPORT_FILE="$REPORT_DIR/linux-ops-report-$(date '+%Y%m%d-%H%M%S').txt"

mkdir -p "$REPORT_DIR"

{
  echo "Linux Operations Report"
  echo "======================="
  echo ""
  echo "Generated at: $(date)"
  echo "Generated by: $(whoami)"
  echo "Hostname: $(hostname)"
  echo ""

  echo "## System information"
  echo "---------------------"
  uname -a
  echo ""
  cat /etc/os-release | head -n 6
  echo ""

  echo "## Uptime"
  echo "---------"
  uptime
  echo ""

  echo "## Memory usage"
  echo "---------------"
  free -h
  echo ""

  echo "## Disk usage"
  echo "-------------"
  df -h
  echo ""

  echo "## Repository size"
  echo "------------------"
  du -sh ~/devops-lab 2>/dev/null || echo "Repository not found at ~/devops-lab"
  echo ""

  echo "## Top processes by CPU"
  echo "-----------------------"
  ps aux --sort=-%cpu | head -n 8
  echo ""

  echo "## Top processes by memory"
  echo "--------------------------"
  ps aux --sort=-%mem | head -n 8
  echo ""

  echo "## Nginx service status"
  echo "-----------------------"
  if systemctl is-active --quiet nginx; then
    echo "Nginx status: active"
  else
    echo "Nginx status: inactive or not installed"
  fi
  echo ""

  echo "## SSH service status"
  echo "---------------------"
  if systemctl is-active --quiet ssh; then
    echo "SSH status: active"
  else
    echo "SSH status: inactive or not installed"
  fi
  echo ""

  echo "## Listening ports"
  echo "------------------"
  sudo ss -tulpn || true
  echo ""

  echo "## Recent Nginx logs"
  echo "--------------------"
  journalctl -u nginx -n 10 --no-pager 2>/dev/null || echo "No Nginx logs available."
  echo ""

  echo "## Recent SSH logs"
  echo "------------------"
  journalctl -u ssh -n 10 --no-pager 2>/dev/null || echo "No SSH logs available."
  echo ""

  echo "Report finished."

} > "$REPORT_FILE"

echo "Report generated:"
echo "$REPORT_FILE"
echo ""
cat "$REPORT_FILE"