name: devops-compose-day04

services:
  db:
    image: postgres:18-alpine

    environment:
      POSTGRES_DB: "${POSTGRES_DB:-devopsdb}"
      POSTGRES_USER: "${POSTGRES_USER:-devops}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set}"

    volumes:
      - postgres-data:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/001-init.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    restart: unless-stopped

    cpus: "0.50"
    mem_limit: 256m
    mem_reservation: 128m
    pids_limit: 100

    networks:
      - backend-net

  api:
    build:
      context: .
      dockerfile: Dockerfile

    image: devops-compose-scalable-api:day04

    expose:
      - "3000"

    environment:
      APP_NAME: "${APP_NAME:-scalable-compose-api-day04}"
      APP_ENV: "${APP_ENV:-development}"
      PORT: "3000"

      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "${POSTGRES_DB:-devopsdb}"
      DB_USER: "${POSTGRES_USER:-devops}"
      DB_PASSWORD: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD must be set}"

    depends_on:
      db:
        condition: service_healthy
        restart: true

    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', res => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: on-failure:3

    init: true
    stop_grace_period: 10s

    cpus: "0.50"
    mem_limit: 128m
    mem_reservation: 64m
    pids_limit: 100

    networks:
      - frontend-net
      - backend-net

  gateway:
    image: nginx:alpine

    ports:
      - "127.0.0.1:${GATEWAY_HOST_PORT:-8093}:80"

    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      api:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O - http://localhost/gateway-health | grep -q gateway-ok"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

    restart: unless-stopped

    cpus: "0.25"
    mem_limit: 64m
    mem_reservation: 32m
    pids_limit: 50

    networks:
      - frontend-net

volumes:
  postgres-data:

networks:
  frontend-net:
    driver: bridge

  backend-net:
    driver: bridge
    internal: true