FROM node:20-alpine

LABEL maintainer="Bernardo de Castro"
LABEL description="API container for Docker networks lab"

WORKDIR /app

COPY api/package.json ./package.json
COPY api/server.js ./server.js

ENV PORT=3000

EXPOSE 3000

CMD ["npm", "start"]